# Generated by Django 5.2.16 on 2026-08-18 07:53

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_delete_emailverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                validators=[
                    apps.core.validators.FileExtensionAllowlistValidator(
                        [".jpg", ".jpeg", ".png", ".webp"]
                    ),
                    apps.core.validators.FileSizeValidator(5),
                ],
            ),
        ),
    ]
