# Generated by Django 5.2.16 on 2026-08-20 13:23

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_productimage_cart_session_key_product_average_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                validators=[
                    apps.core.validators.FileExtensionAllowlistValidator(
                        [".jpg", ".jpeg", ".png", ".webp"]
                    ),
                    apps.core.validators.FileSizeValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="products/gallery/",
                validators=[
                    apps.core.validators.FileExtensionAllowlistValidator(
                        [".jpg", ".jpeg", ".png", ".webp"]
                    ),
                    apps.core.validators.FileSizeValidator(5),
                ],
            ),
        ),
    ]
