# Generated by Django 5.2.16 on 2026-08-17 11:29

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        ("specialists", "0004_specialist_completed_sessions_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="video",
            name="duration_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="specialists.specialist",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="placement",
            field=models.CharField(
                choices=[
                    ("home_hero", "البانر الرئيسي (الصفحة الرئيسية)"),
                    ("home_small_grid", "شبكة الإعلانات الصغيرة (الصفحة الرئيسية)"),
                ],
                max_length=30,
            ),
        ),
    ]
