# Generated by Django 5.2.16 on 2026-08-19 12:20

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_article_category_article_tags_video_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="article",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="articles/",
                validators=[
                    apps.core.validators.FileExtensionAllowlistValidator(
                        [".jpg", ".jpeg", ".png", ".webp"]
                    ),
                    apps.core.validators.FileSizeValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                upload_to="banners/",
                validators=[
                    apps.core.validators.FileExtensionAllowlistValidator(
                        [".jpg", ".jpeg", ".png", ".webp"]
                    ),
                    apps.core.validators.FileSizeValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="testimonials/",
                validators=[
                    apps.core.validators.FileExtensionAllowlistValidator(
                        [".jpg", ".jpeg", ".png", ".webp"]
                    ),
                    apps.core.validators.FileSizeValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="videos/thumbnails/",
                validators=[
                    apps.core.validators.FileExtensionAllowlistValidator(
                        [".jpg", ".jpeg", ".png", ".webp"]
                    ),
                    apps.core.validators.FileSizeValidator(5),
                ],
            ),
        ),
    ]
