# Generated by Django 5.2.16 on 2026-08-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_video_is_featured_alter_article_cover_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="meta_description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="article",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
