# Generated by Django 5.2.16 on 2026-08-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_article_meta_description_article_meta_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="body_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="article",
            name="meta_description_en",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="article",
            name="meta_title_en",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="article",
            name="title_en",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
