# Generated by Django 5.2.16 on 2026-08-19 12:20

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_default_site_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hero_title", models.CharField(blank=True, max_length=255)),
                ("hero_subtitle", models.TextField(blank=True)),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="homepage/",
                        validators=[
                            apps.core.validators.FileExtensionAllowlistValidator(
                                [".jpg", ".jpeg", ".png", ".webp"]
                            ),
                            apps.core.validators.FileSizeValidator(5),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
