# Generated by Django 5.2.16 on 2026-08-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_homepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='show_articles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='show_benefits',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='show_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='show_hero_banner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='show_how_it_works',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='show_small_banners',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='show_specialty_tags',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='show_stats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='show_testimonials',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='show_videos',
            field=models.BooleanField(default=True),
        ),
    ]
