# Generated by Django 5.2.16 on 2026-08-17 10:40

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="module",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="course",
            name="average_rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="course",
            name="intro_video_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="learning_outcomes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="original_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="reviews_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="source_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_enrollments",
                to="payments.order",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="is_free_preview",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to="courses.enrollment",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "unique_together": {("enrollment", "lesson")},
            },
        ),
    ]
