# Generated by Django 5.2.16 on 2026-08-19 12:20

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_lesson_options_alter_module_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="course",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="courses/covers/",
                validators=[
                    apps.core.validators.FileExtensionAllowlistValidator(
                        [".jpg", ".jpeg", ".png", ".webp"]
                    ),
                    apps.core.validators.FileSizeValidator(5),
                ],
            ),
        ),
    ]
