# Generated by Django 5.2.16 on 2026-08-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_is_featured_alter_course_cover_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "permissions": [("manage_own_courses_only", "Restricted to own courses only")]
            },
        ),
    ]
