# Generated by Django 5.2.16 on 2026-08-20 18:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('ar', 'العربية'), ('en', 'الإنجليزية'), ('fr', 'الفرنسية'), ('de', 'الألمانية'), ('es', 'الإسبانية'), ('it', 'الإيطالية'), ('tr', 'التركية'), ('ur', 'الأردية'), ('zh', 'الصينية')], default='ar', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم'), ('all', 'عام')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
