# Generated by Django 5.2.16 on 2026-08-17 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answeroption",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="assessment",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="assessment",
            name="estimated_minutes",
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="attempt",
            name="session_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="attempt",
            name="share_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessment_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ScoreLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.CharField(
                        choices=[("low", "منخفض"), ("medium", "متوسط"), ("high", "مرتفع")],
                        max_length=10,
                    ),
                ),
                ("min_score", models.IntegerField()),
                ("max_score", models.IntegerField()),
                (
                    "description",
                    models.TextField(
                        help_text="النص الإرشادي المعروض للمستخدم عند وقوعه في هذا المستوى."
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_levels",
                        to="assessments.assessment",
                    ),
                ),
            ],
            options={
                "ordering": ["min_score"],
            },
        ),
        migrations.AddField(
            model_name="attempt",
            name="result_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assessments.scorelevel",
            ),
        ),
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", False), ("session_key__isnull", False), _connector="OR"
                ),
                name="assessments_attempt_has_user_or_session",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scorelevel",
            unique_together={("assessment", "level")},
        ),
    ]
