# Generated by Django 5.2.16 on 2026-08-18 07:53

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportticket",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="support/attachments/",
                validators=[
                    apps.core.validators.FileExtensionAllowlistValidator(
                        [".pdf", ".jpg", ".jpeg", ".png", ".doc", ".docx"]
                    ),
                    apps.core.validators.FileSizeValidator(10),
                ],
            ),
        ),
    ]
