# Generated by Django 5.2.16 on 2026-08-14 19:15

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='category',
            field=models.CharField(blank=True, choices=[('psychiatrist', 'طبيب نفسي'), ('clinical_psychologist', 'معالج نفسي اكلينيكي'), ('counselor', 'مرشد نفسي')], max_length=30),
        ),
        migrations.AddField(
            model_name='specialist',
            name='country_of_residence',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specialist',
            name='full_name_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='specialist',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='specialist',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10),
        ),
        migrations.AddField(
            model_name='specialist',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='specialist',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specialist',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'سيد'), ('mrs', 'سيدة'), ('ms', 'آنسة'), ('dr', 'دكتور')], max_length=10),
        ),
        migrations.CreateModel(
            name='CredentialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='specialists/credentials/')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_documents', to='specialists.specialist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
