# Generated by Django 5.2.16 on 2026-08-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialists", "0002_specialist_birth_year_specialist_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialist",
            name="average_rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="specialist",
            name="next_available_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
