# Generated by Django 5.2.16 on 2026-08-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialists", "0004_specialist_completed_sessions_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialist",
            name="reviews_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
