# Generated by Django 5.2.16 on 2026-08-18 07:53

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialists", "0005_specialist_reviews_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credentialdocument",
            name="file",
            field=models.FileField(
                upload_to="specialists/credentials/",
                validators=[
                    apps.core.validators.FileExtensionAllowlistValidator(
                        [".pdf", ".jpg", ".jpeg", ".png", ".doc", ".docx"]
                    ),
                    apps.core.validators.FileSizeValidator(10),
                ],
            ),
        ),
    ]
