# Generated by Django 5.2.16 on 2026-08-18 18:00

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialists", "0006_alter_credentialdocument_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credentialdocument",
            name="file",
            field=models.FileField(
                upload_to="specialists/credentials/",
                validators=[
                    apps.core.validators.FileExtensionAllowlistValidator(
                        [".pdf", ".jpg", ".jpeg", ".png", ".doc", ".docx"]
                    ),
                    apps.core.validators.FileSizeValidator(10),
                    apps.core.validators.FileContentValidator(
                        {
                            ".doc": [b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1"],
                            ".docx": [b"PK\x03\x04"],
                            ".jpeg": [b"\xff\xd8\xff"],
                            ".jpg": [b"\xff\xd8\xff"],
                            ".pdf": [b"%PDF-"],
                            ".png": [b"\x89PNG\r\n\x1a\n"],
                        }
                    ),
                ],
            ),
        ),
    ]
