# Generated by Django 5.2.16 on 2026-08-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialists", "0007_alter_credentialdocument_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialist",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
