# Generated by Django 5.2.16 on 2026-08-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialists", "0008_specialist_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialist",
            name="can_write_articles",
            field=models.BooleanField(default=False),
        ),
    ]
