# Generated by Django 5.2.16 on 2026-08-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["-scheduled_start"]},
        ),
        migrations.AddField(
            model_name="booking",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="booking",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
