# Generated by Django 5.2.16 on 2026-08-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_options_booking_contact_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="calendar_event_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="booking",
            name="meeting_link",
            field=models.URLField(blank=True),
        ),
    ]
