# Generated by Django 5.2.16 on 2026-08-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_alter_answer_options_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
