# Generated by Django 5.2.16 on 2026-08-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("booking", "booking"),
                    ("order", "order"),
                    ("course", "course"),
                    ("system", "system"),
                    ("forum", "forum"),
                ],
                default="system",
                max_length=20,
            ),
        ),
    ]
